version: '3.2'
services:
  prompt_manager_db:
    image: postgres:latest
    expose: 
      - '5439'
    ports:
      - '5439:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: prompt_manager_dev
